name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # MSRV and nightly
        version: [1.85.0, stable, nightly]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set toolchain
        run: |
          rustup set profile minimal
          rustup override set ${{ matrix.version }}

      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7

      - name: Rustfmt check
        if: matrix.version == '1.85.0'
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Run `cargo test` on workspace
        run: cargo test
